Repository depromeet/algorithm-6th, pull requests merged in 2019-04, with the labels that each got.

#17 [BFS/DFS] 타겟넘버 풀이완료
  team2/DFS/juhyun/Solution01.java
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청

#18 [정렬] K 번째 수 풀이완료
  team1/Sort/byeongguk/Solution01.py
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청

#16 [스택/큐] 프린터, 다리를 지나는 트럭 풀이완료
  team2/Stack/sangeun/Bridge.java
  team2/Stack/sangeun/FunctionDevelop.java
  team2/Stack/sangeun/Printer.java
  team2/Stack/sangeun/StockPrice.java
  team2/Stack/sangeun/Top.java
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청

#19 [스택/큐] 쇠막대기, 프린터 풀이완료
  team2/Stack/yunji/Solution01.java
  team2/Stack/yunji/Solution02.java
Labels: :100: 풀이 완료

#20 [스택/큐] 쇠막대기 문제풀이
  team2/Stack/Seungjin/Solution01.java
Labels: :100: 풀이 완료, :v: 자랑

#34 [정렬] 가장 큰 수 풀이완료
  team1/Sort/byeongguk/Solution02.py
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청

#26 [스택/큐] 쇠막대기 풀이완료, 탑/프린터 풀이중
  team2/Stack/Shinje/IronBar.java
  team2/Stack/Shinje/Printer.java
  team2/Stack/Shinje/Tower.java
Labels: :exclamation: 리뷰 요청, :running_man: 풀이 중

#36 1-3 주 문제 풀이완료
  team1/BF/jihun/Solution01.py
  team1/BF/jihun/Solution02.py
  team1/BF/jihun/Solution03.py
  team1/Hash/jihun/Solution01.py
  team1/Hash/jihun/Solution02.py
  team1/Hash/jihun/Solution03.py
  team1/Hash/jihun/Solution04.py
  team1/Sort/jihun/Solution01.py
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청

#42 [완전탐색] 모의고사 풀이완료
  team1/Search/dongkun/search-1.py
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청

#45 [완전탐색] 모의고사 풀이완료
  team1/BF/jiwon/Solution01.py
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청

#53 [완전탐색] 소수 찾기 풀이완료
  team1/Search/byeongguk/Solution02.py
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청

#54 [완전탐색] 모의고사, 소수찾기 풀이완료, 야구게임 풀이중
  team2/BruteForce/yunji/Solution01.java
  team2/BruteForce/yunji/Solution02.java
  team2/BruteForce/yunji/Solution03.java
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청, :running_man: 풀이 중, :sos: 도움 요청

#43 [완전탐색] 모의고사, 숫자야구, 카펫 풀이완료
  team2/BruteForce/sangeun/Carpet.java
  team2/BruteForce/sangeun/NumberBaseball.java
  team2/BruteForce/sangeun/Test.java
Labels: :-1: 양식 오류, :100: 풀이 완료, :exclamation: 리뷰 요청

#40 [완전탐색] 모의고사,카펫 풀이완료, 소수찾기 풀이중
  team2/BruteForce/juhyun/Solution01.java
  team2/BruteForce/juhyun/Solution02.java
  team2/BruteForce/juhyun/Solution04.java
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청

#50 [완전탐색] 카펫 문제풀이완료
  team2/Search/Hyungsuk/carpet.js
  team2/Search/Hyungsuk/test-score.js
Labels: :-1: 양식 오류, :100: 풀이 완료, :exclamation: 리뷰 요청

#51 [완전탐색] 모의고사 풀이완료, 소수찾기 풀이중
  team2/BruteForce/Shinje/PreTest.java
  team2/BruteForce/Shinje/PrimeNumber.java
Labels: :-1: 양식 오류, :running_man: 풀이 중, :sos: 도움 요청

#38 [완전탐색] 모의고사 풀이완료
  team2/BruteForce/haeseong/모의고사.java
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청, :v: 자랑

#39 [완전탐색] 카펫 풀이완료
  team2/BruteForce/haeseong/카펫.java
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청, :v: 자랑

#37 [완전탐색] 소수 찾기 풀이완료
  team2/BruteForce/haeseong/소수_찾기.java
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청, :v: 자랑

#55 [해시] 베스트앨범 풀이완료
  team1/Hash/byeongguk/Solution04.py
Labels: :100: 풀이 완료, :exclamation: 리뷰 요청

#10 [해시] 전화번호 목록 수정
  team1/Hash/jiwon/solution2.py
Labels: :running_man: 풀이 중

#24 [정렬] K 번째 수 풀이 완료
  team1/Sort/dongkun/KNumber.py
Labels: :-1: 양식 오류, :100: 풀이 완료, :exclamation: 리뷰 요청

#25 [정렬] 가장 큰 수 풀이완료
  team1/Sort/dongkun/BigNumber.py
Labels: :-1: 양식 오류, :100: 풀이 완료, :exclamation: 리뷰 요청

#44 [완전탐색] 카펫 풀이완료
  team1/BF/jihun/Solution04.py
Labels: :-1: 양식 오류, :100: 풀이 완료, :exclamation: 리뷰 요청

#49 [완전탐색] 소수 찾기 풀이 중
  team1/Search/dongkun/search-4.py
Labels: :running_man: 풀이 중

#46 [완전탐색] 소수찾기 풀이중
  team1/BF/jiwon/Solution02.py
Labels: :running_man: 풀이 중, :sos: 도움 요청
